Z-Market/Z-Market/Models/Order.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Z_Market.Models
{
    public class Order
    {
        [Key]
        public int OrderID { get; set; }

        public DateTime DateOrder { get; set; }

        public int CustomerID { get; set; }//ID de la tabla de relacion de customer.

        public OrderStatus OrderStatus { get; set; }//Clase enum.

        [JsonIgnore]
        public virtual Customer Customer { get; set; } //Relacion de uno a varios.
        [JsonIgnore]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }//Lado varios de la clase.


    }
}

Z-Market/Z-Market/ViewModels/OrderView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Z_Market.Models;

namespace Z_Market.ViewModels
{
    public class OrderView
    {
        public Customer Customer { get; set; }
        public ProductOrder Product { get; set; }//Usado solo para "Pintar" los titulos.
        public List<ProductOrder> Products { get; set; }//Aqui es donde se almacenan los datos finales.



    }
}

Z-Market/Z-Market/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Z_Market.Models;
using Z_Market.ViewModels;


namespace Z_Market.Controllers
{
    public class OrdersController : Controller
    {

        private Z_MarketContext db = new Z_MarketContext();

        // GET: Orders
        public ActionResult NewOrder()
        {

            var OrderView = new OrderView();
            OrderView.Customer = new Customer();
            OrderView.Products = new List<ProductOrder>();
            Session["OrderView"] = OrderView;//Variable de session.


            var List = db.Customers.ToList();
            List.Add(new Customer { CustomerID = 0, FirtsName = "[Seleccione un cliente]" });
            List = List.OrderBy(c => c.FullName).ToList();
            ViewBag.CustomerID = new SelectList(List, "CustomerID", "FullName");
            return View(OrderView);
        }


        [HttpPost]
        public ActionResult NewOrder(OrderView OrderView)
        {
            OrderView = Session["OrderView"] as OrderView;

            var customerID = int.Parse(Request["CustomerID"]);




            //Validando que se seleecione un producto.
            if (customerID == 0)
            {

                var List = db.Customers.ToList();
                List.Add(new Customer { CustomerID = 0, FirtsName = "[Seleccione un cliente]" });
                List = List.OrderBy(c => c.FullName).ToList();
                ViewBag.CustomerID = new SelectList(List, "CustomerID", "FullName");
                ViewBag.Error = "Debe seleccionar un Cliente";
                return View(OrderView);

            }


            var customer = db.Customers.Find(customerID);//Buscando el ID del producto que fue solicitado.

            //Validando que se seleecione un producto.
            if (customer == null)
            {

                var List = db.Customers.ToList();
                List.Add(new Customer { CustomerID = 0, FirtsName = "[Seleccione un cliente]" });
                List = List.OrderBy(c => c.FullName).ToList();
                ViewBag.CustomerID = new SelectList(List, "CustomerID", "FullName");
                ViewBag.Error = "Cliente no existe";
                return View(OrderView);

            }


            if (OrderView.Products.Count == 0)
            {

                var List = db.Customers.ToList();
                List.Add(new Customer { CustomerID = 0, FirtsName = "[Seleccione un cliente]" });
                List = List.OrderBy(c => c.FullName).ToList();
                ViewBag.CustomerID = new SelectList(List, "CustomerID", "FullName");
                ViewBag.Error = "Debe ingresar detalle";
                return View(OrderView);

            }



            //Orden transaccional.

            var orderID = 0;


            using (var trasaction = db.Database.BeginTransaction())
            {

                try
                {

                    //Llegado a este apunto todo esta correcto para crear el producto e introducirlo a la base de datos.
                    var order = new Order
                    {
                        CustomerID = customerID,
                        DateOrder = DateTime.Now,
                        OrderStatus = OrderStatus.Created
                    };

                    //Agregando y guardando el producto a la base de datos.
                    db.Orders.Add(order);
                    db.SaveChanges();


                    //Seleccionando el ultimo id que fue creado.
                    orderID = db.Orders.ToList().Select(o => o.OrderID).Max();

                    //For each que recorre las cordenes de los productos.
                    foreach (var item in OrderView.Products)
                    {

                        var orderDetail = new OrderDetail
                        {
                            ID = item.ID,
                            Description = item.Description,
                            price = item.price,
                            Quantity = (decimal)item.Quantity,
                            OrderID = orderID

                        };
                        db.OrderDetail.Add(orderDetail);
                        db.SaveChanges();
                    }
                    //Si no hay error confirmamos la trasaccion.
                    trasaction.Commit();
                }
                catch (Exception ex)
                {
                    trasaction.Rollback();
                    ViewBag.Error = "Error: " + ex.Message;
                    return View(OrderView);
                }

               
            }

            ViewBag.Message = String.Format("La orden {0} ha sido grabada con exito.", orderID);

            var ListC = db.Customers.ToList();
            ListC.Add(new Customer { CustomerID = 0, FirtsName = "[Seleccione un cliente]" });
            ListC = ListC.OrderBy(c => c.FullName).ToList();
            ViewBag.CustomerID = new SelectList(ListC, "CustomerID", "FullName");


            OrderView = new OrderView();
            OrderView.Customer = new Customer();
            OrderView.Products = new List<ProductOrder>();
            Session["OrderView"] = OrderView;//Variable de session.

            return View(OrderView) ;
        }



        public ActionResult AddProduct()
        {
            var List = db.Products.ToList();
            List.Add(new Product{ ID = 0, Description = "[Seleccione un producto]" });
            List = List.OrderBy(p => p.Description).ToList();
            ViewBag.ID = new SelectList(List, "ID", "Description");

            return View();
        }



        [HttpPost]
        public ActionResult AddProduct(ProductOrder ProductOrder)
        {
            var OrderView = Session["OrderView"] as OrderView; //Recuperando el objeto de Orderview desde la variable de session.

            var productID = int.Parse(Request["ID"]);//Obteniendo la respues del formulario.

            //Validando que se seleecione un producto.
            if (productID == 0)
            {

                var List = db.Products.ToList();
                List.Add(new Product { ID = 0, Description = "[Seleccione un producto]" });
                List = List.OrderBy(p => p.Description).ToList();
                ViewBag.ID = new SelectList(List, "ID", "Description");
                ViewBag.Error = "Debe seleccionar un producto";
                return View(ProductOrder);

            }


            var product = db.Products.Find(productID);//Buscando el ID del producto que fue solicitado.

            //Validando que se seleecione un producto.
            if (product == null)
            {

                var List = db.Products.ToList();
                List.Add(new Product { ID = 0, Description = "[Seleccione un producto]" });
                List = List.OrderBy(p => p.Description).ToList();
                ViewBag.ID = new SelectList(List, "ID", "Description");
                ViewBag.Error = "El producto seleccionado NO existe";
                return View(ProductOrder);

            }




            ProductOrder = OrderView.Products.Find(p => p.ID == productID);

            if (ProductOrder == null)
            {

                //Creando y llenando objetos de producto.
                ProductOrder = new ProductOrder
                {
                    Description = product.Description,
                    price = product.price,
                    ID = product.ID,
                    Quantity = float.Parse(Request["Quantity"])
                };

                OrderView.Products.Add(ProductOrder);//Agregando un producto existente.

            }
            else
            {
                ProductOrder.Quantity += float.Parse(Request["Quantity"]);
            }

           

            var ListC = db.Customers.ToList();
            ListC.Add(new Customer { CustomerID = 0, FirtsName = "[Seleccione un cliente]" });
            ListC = ListC.OrderBy(c => c.FullName).ToList();
            ViewBag.CustomerID = new SelectList(ListC, "CustomerID", "FullName");

            return View("NewOrder", OrderView);
        }



























        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Z-Market/Z-Market/Views/Orders/AddProduct.cshtml
@model Z_Market.Models.ProductOrder

@{
                

                ViewBag.Title = "AddProduct";
}

<h2>Add Product</h2>
<h3>@ViewBag.Error</h3>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <div class="form-group">
        @Html.LabelFor(model => model.ID, "ID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ID, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
        </div>
    </div>


    <input type="submit" value="Agregar Producto" class="btn btn-success" />


}

Z-Market/Z-Market/Views/Orders/NewOrder.cshtml
@model Z_Market.ViewModels.OrderView

@{
    ViewBag.Title = "NewOrder";
}

<h2>New Order</h2>
<h3>@ViewBag.Error</h3>
<h3>@ViewBag.Message</h3>

@using (Html.BeginForm("NewOrder", "Orders", FormMethod.Post))
{
    @Html.AntiForgeryToken()


    <div class="form-group">
        @Html.LabelFor(model => model.Customer.CustomerID, "CustomerID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CustomerID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Customer.CustomerID, "", new { @class = "text-danger" })
        </div>
    </div>
    <br /><br /><br />
    @Html.ActionLink("Agregar Producto", "AddProduct", new { }, new { @class="btn btn-primary" })
   <input type="submit" value="Guardar Orden" class="btn btn-success" />


}
 
   <h2>Detalles de Ordenes</h2>
   <table class="table">
       <tr>
           <th>
               @Html.DisplayNameFor(model => model.Product.Description)
           </th>
           <th>
               @Html.DisplayNameFor(model => model.Product.price)
           </th>
           <th>
               @Html.DisplayNameFor(model => model.Product.Quantity)
           </th>
           <th>
               @Html.DisplayNameFor(model => model.Product.Valor)
           </th>
           <th></th>
       </tr>

       @for (int i = 0; i < Model.Products.Count; i++)
       {
       <tr>
           <td>
               @Html.DisplayFor(modelItem => Model.Products[i].Description)
           </td>
           <td>
               @Html.DisplayFor(modelItem => Model.Products[i].price)
           </td>
           <td>
               @Html.DisplayFor(modelItem => Model.Products[i].Quantity)
           </td>
           <td>
               @Html.DisplayFor(modelItem => Model.Products[i].Valor)
           </td>
           <td>
               @Html.ActionLink("Edit", "Edit", new { id = Model.Products[i].ID}) |
               @Html.ActionLink("Delete", "Delete", new {id = Model.Products[i].ID })
           </td>
       </tr>
}

   </table>